name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Triggers the workflow on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          npm install  # Installs dependencies
          npm run build  # Builds the project for deployment

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # The directory where your build output is located (e.g., `dist` for Vite)
